### ISSUE TITLE
Searching with @kitsearch (REST) by Anonymous

### ISSUE THREAD

**Issue by ksuess** [collective/collective.es.plone#19]
I have to change
https://github.com/collective/collective.elastic.plone/blob/f0590e324f4eedbb462a060f1b93c6688d16433d/src/collective/elastic/plone/restapi/kitsearch/post.py#L83
by changing `"allowedRolesAndUsers.keyword": arau,` to `"allowedRolesAndUsers": arau,`
to get results for Anonymous. With the current code, I get no results at all.
My `preprossessing.json` is the official one of https://github.com/collective/collective.elastic.ingest/blob/main/src/collective/elastic/ingest/preprocessings.json

I think with
https://github.com/collective/collective.elastic.ingest/blob/b383f66eb87244fc9683729f813f2ec88a5ba35e/src/collective/elastic/ingest/preprocessings.json#L27C1-L43C5
the above mentioned change is necessary. What do you think?

**Comment by jensens** [comment]
IIRC a terms search does not need the explicit `.keyword` if a list is passed in. So,  AFAICT you're  right. Getting queries right is hard... to be sure please check it well.
